<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>


  <ItemGroup>
    <InternalsVisibleTo Include="VanDinhImport" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.1" />
    <PackageReference Include="QuestPDF" Version="2024.12.3" />
    <PackageReference Include="System.IO.Packaging" Version="9.0.5" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.16.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.14" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
