// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VanDinh.API.Data;

#nullable disable

namespace VanDinh.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720125128_UpdateIntangibleHeritageCategoryConstraint")]
    partial class UpdateIntangibleHeritageCategoryConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VanDinh.API.Models.AboutPage", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"));

                    b.Property<string>("BannerImage")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroductionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroductionVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainContentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainContentVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("AboutId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("AboutPage", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.AboutPageHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryId"));

                    b.Property<int>("AboutId")
                        .HasColumnType("int");

                    b.Property<string>("BannerImage")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("IntroductionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroductionVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainContentEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainContentVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleVi")
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("HistoryId");

                    b.HasIndex("AboutId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("AboutPageHistories", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.ActivityLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(45)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LogId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityName");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.ContactMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.ToTable("ContactMessages", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.Heritage", b =>
                {
                    b.Property<long>("HeritageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HeritageId"));

                    b.Property<string>("AddressEn")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressVi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleMapUrl")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Guardian")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HistoryEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoryVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearBuilt")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HeritageId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Classification");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GoogleMapUrl")
                        .IsUnique()
                        .HasFilter("GoogleMapUrl IS NOT NULL AND IsDeleted = 0");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("NameVi")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Heritage", null, t =>
                        {
                            t.HasCheckConstraint("CK_Heritage_AddressEn_MinLength", "AddressEn IS NULL OR LEN(TRIM(AddressEn)) >= 5");

                            t.HasCheckConstraint("CK_Heritage_AddressVi_MinLength", "AddressVi IS NULL OR LEN(TRIM(AddressVi)) >= 5");

                            t.HasCheckConstraint("CK_Heritage_Classification", "Classification IN ('national', 'city', 'unranked')");

                            t.HasCheckConstraint("CK_Heritage_DescriptionEn_MinLength", "DescriptionEn IS NULL OR LEN(TRIM(DescriptionEn)) >= 30");

                            t.HasCheckConstraint("CK_Heritage_DescriptionVi_MinLength", "DescriptionVi IS NULL OR LEN(TRIM(DescriptionVi)) >= 30");

                            t.HasCheckConstraint("CK_Heritage_HistoryEn_MinLength", "HistoryEn IS NULL OR LEN(TRIM(HistoryEn)) >= 50");

                            t.HasCheckConstraint("CK_Heritage_HistoryVi_MinLength", "HistoryVi IS NULL OR LEN(TRIM(HistoryVi)) >= 50");

                            t.HasCheckConstraint("CK_Heritage_NameEn_NotEmpty", "LEN(TRIM(NameEn)) >= 5");

                            t.HasCheckConstraint("CK_Heritage_NameVi_NotEmpty", "LEN(TRIM(NameVi)) >= 5");

                            t.HasCheckConstraint("CK_Heritage_Status", "Status IN ('active', 'maintenance', 'closed')");

                            t.HasCheckConstraint("CK_Heritage_YearBuilt", "YearBuilt IS NULL OR (TRY_CAST(YearBuilt AS INT) IS NOT NULL AND TRY_CAST(YearBuilt AS INT) >= 100 AND TRY_CAST(YearBuilt AS INT) <= YEAR(GETDATE()))");
                        });
                });

            modelBuilder.Entity("VanDinh.API.Models.HeritageCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HeritageCategories", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.HeritageDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentId"));

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("HeritageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("DocumentId");

                    b.HasIndex("HeritageId");

                    b.ToTable("HeritageDocuments", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.HeritageImage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("HeritageId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ImageId");

                    b.HasIndex("HeritageId");

                    b.ToTable("HeritageImages", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.HeritageVideo", b =>
                {
                    b.Property<long>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VideoId"));

                    b.Property<long>("HeritageId")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("VideoType")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VideoId");

                    b.HasIndex("HeritageId");

                    b.ToTable("HeritageVideos", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.IntangibleHeritage", b =>
                {
                    b.Property<long>("IntangibleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntangibleId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Community")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("CulturalSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatusEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomsAndOfferings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingArtisans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExistingProtectionMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FestivalDuration")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FestivalLocation")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FestivalTime")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FolkGames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormationHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GalleryImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeritageValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeritageValueEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricalDevelopment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Learners")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherHumanResources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherNames")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Practitioners")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedProtectionMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RelatedDocuments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedDocumentsEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepresentativePersons")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RiskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RitualObjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RitualParticipants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RitualProcess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeachingArtisans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThreatLevel")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TraditionalPerformances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransmissionMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WorshipObjects")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntangibleId");

                    b.HasIndex("Category");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("NameVi")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("IntangibleHeritage", null, t =>
                        {
                            t.HasCheckConstraint("CK_IntangibleHeritage_Category", "Category IN ('knowledge', 'festival', 'belief', 'craft')");
                        });
                });

            modelBuilder.Entity("VanDinh.API.Models.MediaFile", b =>
                {
                    b.Property<long>("MediaFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MediaFileId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MediaFileId");

                    b.HasIndex("MediaType");

                    b.HasIndex("Url");

                    b.ToTable("MediaFiles", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.RelatedLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("LinkId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("RelatedLinks", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.SystemSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FooterText")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TiktokUrl")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("WebsiteName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SettingId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("VanDinh.API.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("Email IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Username_Format", "Username LIKE '[a-zA-Z0-9_]%' AND LEN(Username) >= 4");
                        });
                });

            modelBuilder.Entity("VanDinh.API.Models.AboutPage", b =>
                {
                    b.HasOne("VanDinh.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDinh.API.Models.AboutPageHistory", b =>
                {
                    b.HasOne("VanDinh.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDinh.API.Models.ActivityLog", b =>
                {
                    b.HasOne("VanDinh.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VanDinh.API.Models.Heritage", b =>
                {
                    b.HasOne("VanDinh.API.Models.HeritageCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDinh.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDinh.API.Models.HeritageDocument", b =>
                {
                    b.HasOne("VanDinh.API.Models.Heritage", null)
                        .WithMany("Documents")
                        .HasForeignKey("HeritageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDinh.API.Models.HeritageImage", b =>
                {
                    b.HasOne("VanDinh.API.Models.Heritage", null)
                        .WithMany("Images")
                        .HasForeignKey("HeritageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDinh.API.Models.HeritageVideo", b =>
                {
                    b.HasOne("VanDinh.API.Models.Heritage", null)
                        .WithMany("Videos")
                        .HasForeignKey("HeritageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VanDinh.API.Models.RelatedLink", b =>
                {
                    b.HasOne("VanDinh.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanDinh.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VanDinh.API.Models.SystemSetting", b =>
                {
                    b.HasOne("VanDinh.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VanDinh.API.Models.User", b =>
                {
                    b.HasOne("VanDinh.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VanDinh.API.Models.Heritage", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Images");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
