/*==========================================================
    PROJECT : VAN DINH DIGITAL HERITAGE MAP
    DATABASE: VanDinhDigitalMap
    PURPOSE : SQL Server schema + seed data for this project

    Run:
    sqlcmd -S localhost -E -i backend\database\VanDinhDigitalMap.sql

    Auto-generated by export-db.ps1 -- do not edit manually.
==========================================================*/
USE master;
GO

IF DB_ID(N'VanDinhDigitalMap') IS NOT NULL
BEGIN
    ALTER DATABASE VanDinhDigitalMap
    SET SINGLE_USER
    WITH ROLLBACK IMMEDIATE;

    DROP DATABASE VanDinhDigitalMap;
END
GO

CREATE DATABASE VanDinhDigitalMap;
GO

USE VanDinhDigitalMap;
GO
CREATE TABLE Roles (
    RoleId int NOT NULL
,
    RoleName nvarchar(100) NOT NULL
,
    (2 rows affected)

)

GO

CREATE TABLE Users (
    UserId bigint NOT NULL
,
    RoleId int NOT NULL
,
    Username nvarchar(100) NOT NULL
,
    PasswordHash nvarchar(510) NOT NULL
,
    FullName nvarchar(200) NULL
,
    Email nvarchar(200) NULL
,
    Status bit NOT NULL DEFAULT (CONVERT([bit],(1)))
,
    CreatedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    UpdatedAt datetime2 NULL
,
    (9 rows affected)

)

GO

CREATE TABLE HeritageCategories (
    CategoryId int NOT NULL
,
    Code nvarchar(60) NOT NULL
,
    NameVi nvarchar(200) NOT NULL
,
    NameEn nvarchar(200) NOT NULL
,
    IconUrl nvarchar(510) NULL
,
    (5 rows affected)

)

GO

CREATE TABLE Heritage (
    HeritageId bigint NOT NULL
,
    PublicId nvarchar(40) NOT NULL
,
    Code nvarchar(100) NOT NULL
,
    CategoryId int NOT NULL
,
    NameVi nvarchar(510) NOT NULL
,
    NameEn nvarchar(510) NOT NULL
,
    Slug nvarchar(510) NOT NULL
,
    Classification nvarchar(40) NOT NULL
,
    Status nvarchar(40) NOT NULL
,
    AddressVi nvarchar(1000) NULL
,
    AddressEn nvarchar(1000) NULL
,
    Latitude decimal NULL
,
    Longitude decimal NULL
,
    DescriptionVi nvarchar(MAX) NULL
,
    DescriptionEn nvarchar(MAX) NULL
,
    HistoryVi nvarchar(MAX) NULL
,
    HistoryEn nvarchar(MAX) NULL
,
    ThumbnailUrl nvarchar(1000) NULL
,
    YearBuilt nvarchar(200) NULL
,
    Guardian nvarchar(510) NULL
,
    QrCodeUrl nvarchar(1000) NULL
,
    GoogleMapUrl nvarchar(2000) NULL
,
    IsDeleted bit NOT NULL DEFAULT (CONVERT([bit],(0)))
,
    DeletedAt datetime2 NULL
,
    CreatedBy bigint NOT NULL
,
    CreatedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    UpdatedAt datetime2 NULL
,
    (27 rows affected)

)

GO

CREATE TABLE HeritageImages (
    ImageId bigint NOT NULL
,
    HeritageId bigint NOT NULL
,
    ImageUrl nvarchar(1000) NOT NULL
,
    Caption nvarchar(510) NULL
,
    SortOrder int NOT NULL DEFAULT ((0))
,
    UploadedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    (6 rows affected)

)

GO

CREATE TABLE HeritageVideos (
    VideoId bigint NOT NULL
,
    HeritageId bigint NOT NULL
,
    Title nvarchar(510) NULL
,
    VideoType nvarchar(40) NULL
,
    VideoUrl nvarchar(1000) NULL
,
    ThumbnailUrl nvarchar(1000) NULL
,
    UploadedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    (7 rows affected)

)

GO

CREATE TABLE HeritageDocuments (
    DocumentId bigint NOT NULL
,
    HeritageId bigint NOT NULL
,
    FileName nvarchar(510) NULL
,
    FileUrl nvarchar(1000) NULL
,
    FileType nvarchar(40) NULL
,
    FileSize bigint NULL
,
    UploadedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    (7 rows affected)

)

GO

CREATE TABLE IntangibleHeritage (
    IntangibleId bigint NOT NULL
,
    PublicId nvarchar(40) NOT NULL
,
    NameVi nvarchar(510) NOT NULL
,
    NameEn nvarchar(510) NOT NULL
,
    Category nvarchar(60) NOT NULL
,
    DescriptionVi nvarchar(MAX) NULL
,
    DescriptionEn nvarchar(MAX) NULL
,
    ImageUrl nvarchar(1000) NULL
,
    VideoUrl nvarchar(1000) NULL
,
    IsDeleted bit NOT NULL DEFAULT (CONVERT([bit],(0)))
,
    CreatedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    UpdatedAt datetime2 NULL
,
    CreatedBy bigint NOT NULL DEFAULT (CONVERT([bigint],(1)))
,
    UpdatedBy bigint NULL
,
    Community nvarchar(500) NULL
,
    CulturalSpace nvarchar(MAX) NULL
,
    CurrentStatus nvarchar(MAX) NULL
,
    CustomsAndOfferings nvarchar(MAX) NULL
,
    ExistingArtisans nvarchar(MAX) NULL
,
    ExistingProtectionMeasures nvarchar(MAX) NULL
,
    FestivalDuration nvarchar(200) NULL
,
    FestivalLocation nvarchar(500) NULL
,
    FestivalTime nvarchar(200) NULL
,
    FolkGames nvarchar(MAX) NULL
,
    FormationHistory nvarchar(MAX) NULL
,
    GalleryImages nvarchar(MAX) NULL
,
    HeritageValue nvarchar(MAX) NULL
,
    HistoricalDevelopment nvarchar(MAX) NULL
,
    Learners nvarchar(MAX) NULL
,
    Location nvarchar(500) NULL
,
    Origin nvarchar(MAX) NULL
,
    OtherHumanResources nvarchar(MAX) NULL
,
    OtherNames nvarchar(500) NULL
,
    Practitioners nvarchar(MAX) NULL
,
    ProposedProtectionMeasures nvarchar(MAX) NULL
,
    RelatedDocuments nvarchar(MAX) NULL
,
    RepresentativePersons nvarchar(500) NULL
,
    RiskDescription nvarchar(MAX) NULL
,
    RitualObjects nvarchar(MAX) NULL
,
    RitualParticipants nvarchar(MAX) NULL
,
    RitualProcess nvarchar(MAX) NULL
,
    TeachingArtisans nvarchar(MAX) NULL
,
    ThreatLevel nvarchar(100) NULL
,
    TraditionalPerformances nvarchar(MAX) NULL
,
    TransmissionMethod nvarchar(MAX) NULL
,
    WorshipObjects nvarchar(MAX) NULL
,
    OriginEn nvarchar(MAX) NULL
,
    HeritageValueEn nvarchar(MAX) NULL
,
    CurrentStatusEn nvarchar(MAX) NULL
,
    RelatedDocumentsEn nvarchar(MAX) NULL
,
    (50 rows affected)

)

GO

CREATE TABLE MonthlyUpdates (
    UpdateId int NOT NULL
,
    MonthLabel nvarchar(40) NOT NULL
,
    DisplayVi nvarchar(100) NOT NULL
,
    DisplayEn nvarchar(100) NOT NULL
,
    UpdateCount int NOT NULL DEFAULT ((0))
,
    (5 rows affected)

)

GO

CREATE TABLE AboutPage (
    AboutId int NOT NULL
,
    BannerImage nvarchar(1000) NULL
,
    UpdatedBy bigint NOT NULL
,
    UpdatedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    ContactInfo nvarchar(MAX) NULL
,
    IntroductionEn nvarchar(MAX) NOT NULL DEFAULT (N'')
,
    IntroductionVi nvarchar(MAX) NOT NULL DEFAULT (N'')
,
    MainContentEn nvarchar(MAX) NOT NULL DEFAULT (N'')
,
    MainContentVi nvarchar(MAX) NOT NULL DEFAULT (N'')
,
    TitleEn nvarchar(400) NOT NULL DEFAULT (N'')
,
    TitleVi nvarchar(400) NOT NULL DEFAULT (N'')
,
    (11 rows affected)

)

GO

CREATE TABLE ActivityLogs (
    LogId bigint NOT NULL
,
    UserId bigint NOT NULL
,
    Action nvarchar(100) NULL
,
    EntityName nvarchar(200) NULL
,
    EntityId bigint NULL
,
    Description nvarchar(MAX) NULL
,
    CreatedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    IpAddress nvarchar(90) NULL
,
    (8 rows affected)

)

GO

CREATE TABLE SystemSettings (
    SettingId int NOT NULL
,
    WebsiteName nvarchar(510) NULL
,
    LogoUrl nvarchar(1000) NULL
,
    FooterText nvarchar(1000) NULL
,
    ContactEmail nvarchar(510) NULL
,
    Phone nvarchar(100) NULL
,
    Address nvarchar(510) NULL
,
    FacebookUrl nvarchar(1000) NULL
,
    TiktokUrl nvarchar(1000) NULL
,
    UpdatedBy bigint NULL
,
    UpdatedAt datetime2 NOT NULL DEFAULT (sysutcdatetime())
,
    YoutubeUrl nvarchar(1000) NULL
,
    (12 rows affected)

)

GO

