<#
.SYNOPSIS
    Exports the VanDinhDigitalMap SQL Server database as a full schema+data script.

.DESCRIPTION
    Generates backend/database/VanDinhDigitalMap.sql from the live database.
    Used by the pre-commit hook to automatically snapshot database changes.

    Tries, in order:
      1. sqlpackage.exe   (Data-Tier Application Framework – cleanest output)
      2. SMO               (SqlServer PowerShell module)
      3. sqlcmd            (basic schema-only fallback)
#>

$ErrorActionPreference = "Stop"

$RepoRoot = git rev-parse --show-toplevel 2>$null
if (-not $RepoRoot) { $RepoRoot = Split-Path -Parent $PSScriptRoot }

$Server      = "localhost"
$Database    = "VanDinhDigitalMap"
$OutputFile  = [System.IO.Path]::Combine($RepoRoot, "backend", "database", "VanDinhDigitalMap.sql")

# ---- Helpers ----
function Write-Header($Path) {
@"
/*==========================================================
    PROJECT : VAN DINH DIGITAL HERITAGE MAP
    DATABASE: VanDinhDigitalMap
    PURPOSE : SQL Server schema + seed data for this project

    Run:
    sqlcmd -S localhost -E -i backend\database\VanDinhDigitalMap.sql

    Auto-generated by export-db.ps1 -- do not edit manually.
==========================================================*/
"@ | Set-Content -Path $Path -Encoding UTF8
}

function Add-ContentBatch($Path, $Text) {
    Add-Content -Path $Path -Value $Text -Encoding UTF8
    Add-Content -Path $Path -Value "`r`nGO`r`n" -Encoding UTF8
}

# ---- Strategy 1 : sqlpackage.exe (SSDT) ----
function Invoke-SqlPackage {
    $exe = Get-Command "sqlpackage.exe" -ErrorAction SilentlyContinue
    if (-not $exe) { return $false }

    Write-Host "[export-db] Using sqlpackage.exe ..."

    $tempFile = [System.IO.Path]::GetTempFileName()
    try {
        $proc = Start-Process -FilePath $exe.Source -NoNewWindow -PassThru -Wait -ArgumentList @(
            "/Action:Script"
            "/SourceServerName:$Server"
            "/SourceDatabaseName:$Database"
            "/TargetFile:$tempFile"
            '/p:ScriptStatistics="None"'
            '/p:ScriptExtendedProperties="True"'
            "/p:TargetDatabaseName=$Database"
        )
        if ($proc.ExitCode -ne 0) { return $false }

        Write-Header $OutputFile
        Get-Content $tempFile | Add-Content -Path $OutputFile -Encoding UTF8
        Write-Host "[export-db] Database snapshot written to $OutputFile"
        return $true
    }
    finally { Remove-Item $tempFile -ErrorAction SilentlyContinue }
}

# ---- Strategy 2 : SMO (SqlServer module) ----
function Invoke-SMO {
    $mod = Get-Module -Name SqlServer -ListAvailable
    if (-not $mod) { return $false }

    try { Import-Module SqlServer -Force -ErrorAction Stop }
    catch { return $false }

    Write-Host "[export-db] Using SqlServer module (SMO) ..."

    $srv = New-Object Microsoft.SqlServer.Management.Smo.Server $Server
    $db  = $srv.Databases[$Database]
    if (-not $db) { throw "Database '$Database' not found on $Server" }

    $so             = New-Object Microsoft.SqlServer.Management.Smo.ScriptingOptions
    $so.IncludeIfNotExists    = $true
    $so.DriAll                = $true
    $so.Indexes               = $true
    $so.Triggers              = $true
    $so.ScriptBatchTerminator = $true
    $so.SchemaQualify         = $true
    $so.NoCommandTerminator   = $false
    $so.IncludeHeaders        = $false

    $scr = New-Object System.Text.StringBuilder

    # Schema header
    [void]$scr.AppendLine("USE master;")
    [void]$scr.AppendLine("GO")
    [void]$scr.AppendLine("")
    [void]$scr.AppendLine("IF DB_ID(N'VanDinhDigitalMap') IS NOT NULL")
    [void]$scr.AppendLine("BEGIN")
    [void]$scr.AppendLine("    ALTER DATABASE VanDinhDigitalMap SET SINGLE_USER WITH ROLLBACK IMMEDIATE;")
    [void]$scr.AppendLine("    DROP DATABASE VanDinhDigitalMap;")
    [void]$scr.AppendLine("END")
    [void]$scr.AppendLine("GO")
    [void]$scr.AppendLine("")
    [void]$scr.AppendLine("CREATE DATABASE VanDinhDigitalMap;")
    [void]$scr.AppendLine("GO")
    [void]$scr.AppendLine("")
    [void]$scr.AppendLine("USE VanDinhDigitalMap;")
    [void]$scr.AppendLine("GO")
    [void]$scr.AppendLine("")

    # Tables
    foreach ($table in $db.Tables | Where-Object { -not $_.IsSystemObject }) {
        $sc = $table.Script($so)
        if ($sc) {
            [void]$scr.AppendLine(($sc -join "`r`nGO`r`n") + "`r`nGO`r`n")
        }
    }

    # Views
    foreach ($view in $db.Views | Where-Object { -not $_.IsSystemObject }) {
        $sc = $view.Script($so)
        if ($sc) {
            [void]$scr.AppendLine(($sc -join "`r`nGO`r`n") + "`r`nGO`r`n")
        }
    }

    Write-Header $OutputFile
    Add-Content -Path $OutputFile -Value $scr.ToString() -Encoding UTF8

    # ---- Seed data ----
    $tableNames = @(
        "Roles", "Users", "HeritageCategories", "Heritage",
        "HeritageImages", "HeritageVideos", "HeritageDocuments",
        "IntangibleHeritage", "MonthlyUpdates", "AboutPage",
        "ActivityLogs", "SystemSettings"
    )

    foreach ($tName in $tableNames) {
        $rows = Invoke-Sqlcmd -ServerInstance $Server -Database $Database -Query "SELECT * FROM [$tName] ORDER BY (SELECT NULL)" -MaxCharLength 1000000
        if (-not $rows) { continue }

        # Get column names from the DataTable
        $cols = $rows.Columns | Where-Object { $_.ColumnName -ne "RowError" } | ForEach-Object { $_.ColumnName }
        Add-Content -Path $OutputFile -Value "INSERT INTO [$tName] ($($cols -join ', ')) VALUES" -Encoding UTF8

        $rowVals = @()
        foreach ($row in $rows) {
            $vals = @()
            foreach ($col in $cols) {
                $val = $row.$col
                if ($null -eq $val -or [DBNull]::Value.Equals($val)) {
                    $vals += "NULL"
                } elseif ($val -is [string]) {
                    $vals += "N'$($val -replace "'", "''")'"
                } elseif ($val -is [DateTime]) {
                    $vals += "N'$($val.ToString('yyyy-MM-dd HH:mm:ss'))'"
                } elseif ($val -is [bool]) {
                    $vals += if ($val) { "1" } else { "0" }
                } elseif ($val -is [byte]) {
                    $vals += "0x$([System.BitConverter]::ToString($val).Replace('-', '').ToLower())"
                } else {
                    $vals += "$val"
                }
            }
            $rowVals += "($($vals -join ', '))"
        }
        Add-Content -Path $OutputFile -Value ($rowVals -join ",`r`n") -Encoding UTF8
        Add-Content -Path $OutputFile -Value "`r`nGO`r`n" -Encoding UTF8
    }

    Write-Host "[export-db] Database snapshot written to $OutputFile"
    return $true
}

# ---- Strategy 3 : sqlcmd fallback (schema-only) ----
function Invoke-SqlCmdFallback {
    $exe = Get-Command "sqlcmd" -ErrorAction SilentlyContinue
    if (-not $exe) { return $false }

    Write-Host "[export-db] Using sqlcmd (schema-only fallback) ..."
    Write-Header $OutputFile

    # Static CREATE DATABASE block (matching the existing file)
@"
USE master;
GO

IF DB_ID(N'VanDinhDigitalMap') IS NOT NULL
BEGIN
    ALTER DATABASE VanDinhDigitalMap
    SET SINGLE_USER
    WITH ROLLBACK IMMEDIATE;

    DROP DATABASE VanDinhDigitalMap;
END
GO

CREATE DATABASE VanDinhDigitalMap;
GO

USE VanDinhDigitalMap;
GO
"@ | Add-Content -Path $OutputFile -Encoding UTF8

    # Export each table schema
    $tables = @(
        "Roles", "Users", "HeritageCategories", "Heritage",
        "HeritageImages", "HeritageVideos", "HeritageDocuments",
        "IntangibleHeritage", "MonthlyUpdates", "AboutPage",
        "ActivityLogs", "SystemSettings"
    )

    foreach ($t in $tables) {
        $def = & $exe.Source -S $Server -E -d $Database -Q "SELECT COLUMN_NAME + ' ' + DATA_TYPE + CASE WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL THEN '(' + CASE WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN 'MAX' ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) END + ')' ELSE '' END + CASE WHEN IS_NULLABLE = 'NO' THEN ' NOT NULL' ELSE ' NULL' END + ISNULL(' DEFAULT ' + COLUMN_DEFAULT, '') AS col_def FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '$t' ORDER BY ORDINAL_POSITION" -h -1 -W -s "`t" 2>&1
        Add-Content -Path $OutputFile -Value "CREATE TABLE $t (" -Encoding UTF8
        $first = $true
        foreach ($line in $def) {
            if (-not $line.Trim()) { continue }
            if (-not $first) { Add-Content -Path $OutputFile -Value "," -Encoding UTF8 }
            Add-Content -Path $OutputFile -Value "    $($line.Trim())" -Encoding UTF8
            $first = $false
        }
        Add-Content -Path $OutputFile -Value "`r`n)" -Encoding UTF8
        Add-Content -Path $OutputFile -Value "`r`nGO`r`n" -Encoding UTF8
    }

    Write-Host "[export-db] Database snapshot written to $OutputFile (sqlcmd fallback)"
    return $true
}

# ---- Main ----
Write-Host "[export-db] Exporting database '$Database' from '$Server' ..."

if (Invoke-SqlPackage)      { exit 0 }
if (Invoke-SMO)            { exit 0 }
if (Invoke-SqlCmdFallback) { exit 0 }

Write-Host "[export-db] ERROR: No export tool available (sqlpackage, SqlServer module, or sqlcmd)." -ForegroundColor Red
exit 1
